package ipp.aci.boleia.dominio.enums;

/**
 * Chave para configurações do sistema
 */
public enum ChaveConfiguracaoSistema {

    PORCENTAGEM_CALCULO_PRECO_MEDIO,
    TOLERANCIA_HODOMETRO_HORIMETRO,
    SERVICO_ENVIO_SMS,
    VERSAO_MINIMA_APP_MOTORISTA_IOS,
    ULTIMA_VERSAO_APP_MOTORISTA_IOS,
    VERSAO_MINIMA_APP_MOTORISTA_ANDROID,
    ULTIMA_VERSAO_APP_MOTORISTA_ANDROID,
    TELEFONE_CENTRAL_ATENDIMENTO_DDD,
    TELEFONE_CENTRAL_ATENDIMENTO_NUMERO,
    CELULAR_CENTRAL_ATENDIMENTO_DDD,
    CELULAR_CENTRAL_ATENDIMENTO_NUMERO,
    VERSAO_MINIMA_APP_FROTISTA_IOS,
    ULTIMA_VERSAO_APP_FROTISTA_IOS,
    VERSAO_MINIMA_APP_FROTISTA_ANDROID,
    ULTIMA_VERSAO_APP_FROTISTA_ANDROID,
    JWT_INTEGRADOR,
    REFRESH_TOKEN,
    SALT_REFRESH_TOKEN,
    ROTINA_AVISO_DEBITO_DEZ,
    ROTINA_AVISO_DEBITO_DEZESSEIS
}
