package ipp.aci.boleia.dominio.enums;

/**
 * Enum com os tipos de erros de validacao associados a uma {@link ipp.aci.boleia.dominio.AutorizacaoPagamento}
 *
 */
public enum TipoErroAutorizacaoPagamento {

    PEDIDO_INVALIDO,
    PEDIDO_COMBUSTIVEL_INVALIDO,
    CODIGO_ABASTECIMENTO_INVALIDO,
    FROTA_INVALIDA,
    FROTA_INATIVA,
    VEICULO_INVALIDO,
    VEICULO_INATIVO,
    HODOMETRO_HORIMETRO_INVALIDO,
    HODOMETRO_INVALIDO,
    HORIMETRO_INVALIDO,
    MOTORISTA_INVALIDO,
    MOTORISTA_INATIVO,
    PONTO_VENDA_INVALIDO,
    PONTO_VENDA_INATIVO,
    VIP_OBRIGATORIO,
    VIP_AUTENTICACAO_INVALIDA,
    ABASTECIMENTO_FINALIZADO,
    DISPOSITIVO_INVALIDO,
    DISPOSITIVO_INATIVO,
    SENHA_CONTINGENCIA_INVALIDA,
    SENHA_MOTORISTA_INVALIDA,
    UNIDADE_INATIVA;

}
